when:
  - event: [push]
steps:
  - name: build
    image: woodpeckerci/plugin-kaniko
    settings:
      registry: gitea.cazzzer.com
      repo: ${CI_REPO,,}
      # replace '/' in branch name
      tags: ${CI_COMMIT_BRANCH/\//-}
      cache: true
      username:
        from_secret: registry-username
      password:
        from_secret: registry-password
